//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
    [Window(UILayer.UI, location : "UI_Menu")]
    public partial class UI_Menu : UIWindow
    {
        #region 脚本工具生成的代码

        private UIBindComponent m_bindComponent;
        private Button m_btnPlay = null!;

        protected override void ScriptGenerator()
        {
            m_bindComponent = gameObject.GetComponent<UIBindComponent>();
            m_btnPlay = m_bindComponent.GetComponent<Button>(0);
            m_btnPlay.onClick.AddListener(UniTask.UnityAction(OnClickPlayBtn));
        }

        #endregion

        #region 事件

        private partial UniTaskVoid OnClickPlayBtn();

        #endregion
    }
}
