//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
    public partial class UI_Menu : UIWindow
    {
        #region 事件

        private partial UniTaskVoid OnClickPlayBtn()
        {
            GameEvent.Send("ReadPersistentInfo");
            return default;
        }

        #endregion
    }
}
