//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
    public partial class UI_ProgressBar : UIWindow
    {
        #region 事件

        /// <summary>
        /// 更新加载进度。
        /// </summary>
        /// <param name="progress">加载进度值（0-1）</param>
        public void UpdateProgress(float progress)
        {
            m_sliderLoadingBar.value = progress;
            m_tmpLoadingValue.text = $"{(int)(progress * 100)}%";
        }

        private partial void OnSliderLoadingBarChange(float value)
        {
            // 进度条值改变时的处理逻辑（可选）
        }

        #endregion
    }
}
