//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
    [Window(UILayer.UI, location : "UI_ProgressBar")]
    public partial class UI_ProgressBar : UIWindow
    {
        #region 脚本工具生成的代码

        private UIBindComponent m_bindComponent;
        private Slider m_sliderLoadingBar = null!;
        private TextMeshProUGUI m_tmpLoadingValue = null!;

        protected override void ScriptGenerator()
        {
            m_bindComponent = gameObject.GetComponent<UIBindComponent>();
            m_sliderLoadingBar = m_bindComponent.GetComponent<Slider>(0);
            m_tmpLoadingValue = m_bindComponent.GetComponent<TextMeshProUGUI>(1);
            m_sliderLoadingBar.onValueChanged.AddListener(OnSliderLoadingBarChange);
        }

        #endregion

        #region 事件

        private partial void OnSliderLoadingBarChange(float value);

        #endregion
    }
}
